# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metrics-server
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm:
    releases:
    - name: metrics-server
      chartPath: ../../../.cache/helm/metrics-server-3.13.1.tgz
      namespace: kube-system
      skipBuildDependencies: true
      setValues:
        image.tag: v0.8.1
        args[0]: --kubelet-insecure-tls
