# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra
requires:
- path: metrics-server/skaffold.yaml
  configs:
  - metrics-server
- path: prometheus/skaffold.yaml
  configs:
  - prometheus
