# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: prometheus-operator-crds
manifests:
  helm:
    releases:
    - name: prometheus-operator-crds
      chartPath: ../../../.cache/helm/prometheus-operator-crds-31.0.0.tgz
      namespace: monitoring
      skipBuildDependencies: true
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl:
    flags:
      apply:
      - --server-side
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: prometheus
requires:
- configs:
  - prometheus-operator-crds
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm:
    releases:
    - name: prometheus
      chartPath: ../../../.cache/helm/kube-prometheus-stack-88.1.5.tgz
      namespace: monitoring
      createNamespace: true
      skipBuildDependencies: true
      valuesFiles:
      - ../prometheus/values.yaml
      setValues:
        crds.enabled: false
