# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Security note: No untrusted input is used in run commands.

name: Stale Check

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Mark Stale Issues and PRs
    runs-on: linux-amd64-cpu4
    steps:
      - uses: dsx-ai-factory/dsx-github-actions/.github/actions/stale-check@0969f64c3efa9e757135cbf457ea13cde4c3fa38 # v1.17.0
